

test:
  dev: 로컬입니다
  list1:
    - data1이건 로컬
    - data2 이건 로컬
  list2:
    - data1이건 로컬
    - data2
    - data2 이건 로컬이 가장 많음
  list3:
    - data1이건 로컬
    - data3 같으면 누구꺼? 나는 로컬
  map: 
    key1: key1Value
    key2: key2Value이건 로컬
    key3: key3ValueLocal
    key4: key4Value
    
---
spring.profiles: dev
test:
  dev: 개발입니다
  list1:
    - data1이건 개발
    - data2
  list2:
    - data1이건 개발

  list3:
    - data1이건 개발
    - data3 같으면 누구꺼? 나는 개발    
  map: 
    key1: key1Value
    key2: key2Value이건 개발
    key3: key3ValueDEV
    key4: key4Value    